"""add pass

Revision ID: 34df5ad70f45
Revises: 81b564ad83eb
Create Date: 2020-07-14 17:28:12.211678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34df5ad70f45'
down_revision = '81b564ad83eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mhs', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mhs', 'password')
    # ### end Alembic commands ###
